---
apiVersion: v1
kind: Service
metadata:
  name: kafka-rest
  labels:
    app: kafka-rest
spec:
  ports:
    - name: rest-proxy
      port: 8082
  selector:
    app: kafka-rest
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka-rest
  labels:
    app: kafka-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-rest
  template:
    metadata:
      labels:
        app: kafka-rest
    spec:
      containers:
        - name: kafka-rest-server
          image: "confluentinc/cp-kafka-rest:5.0.1"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: rest-proxy
              containerPort: 8082
              protocol: TCP
          env:
          - name: KAFKA_REST_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KAFKA_REST_PORT
            value: ""
          - name: KAFKA_REST_BOOSTRAP_SERVERS
            value: kafka:9092
          - name: KAFKA_REST_ZOOKEEPER_CONNECT
            value: kafka-zookeeper:2181
          - name: KAFKA_REST_SCHEMA_REGISTRY_URL
            value: kafka-schema-registry:8081
          - name: KAFKA_REST_LISTENERS
            value: http://0.0.0.0:8082
