---
apiVersion: v1
kind: Service
metadata:
  name: kafka-schema-registry-k8s
  labels:
    app: schema-registry
spec:
  ports:
    - name: schema-registry
      port: 8081
  selector:
    app: schema-registry
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-schema-registry-k8s
  labels:
    app: schema-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: "confluentinc/cp-schema-registry:5.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /subjects
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /subjects
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          env:
          - name: SCHEMA_REGISTRY_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
            value: 'kafka-zookeeper:2181'
            
